### ISSUE TITLE
Fristen

### ISSUE THREAD

**Issue by Alexgamer470** [xflow3r/EP2-solutions#2]
Hast du vor die Aufgabenblätter ab jetzt immer nach der Abgabefrist hochzuladen? (Will es nur für meine zeitliche Einteilung wissen, weil wenn ich bei einer Teilaufgabe nicht weiterwusste habe ich sie bis jetzt ausgelassen und mich auf die Lösung in diesem Repo verlassen aber das geht jetzt nicht mehr).

**Comment by xflow3r** [comment]
nein, schau eigentlich immer das ich meine lösung vor der deadline oben hab. War nur letzte Woche echt busy wegen anderen Sachen - deswegen speedrunne ich die Abgabe jetzt gerade (bin noch stuck bei conditions).
Hab eigentlich immer vor der abgabe hochgeladen (bei ab5 wurde die deadline ja auf den 21. Mai extended)

**Comment by Alexgamer470** [comment]
Okay, kein Stress! Ist wegen letzter Woche eh verständlich, weil da hatten wir ja auch Test und so! Danke nochmal für deine Mühen! :D
